name: replace 0.0.0.0 with 127.0.0.1

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#    branches: 
#      - master
  schedule:
    # - cron: "0 0/6 * * *"
    - cron: "0 0/1 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests
      run: |
        pip install requests
    - name: Do the do
      run: | 
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python main.py   
    - name: download rclone.conf
      run: |
        curl -L ${{ secrets.HMMMM_RCLONE_CONF_DOWNLOAD_URL}} > ./rclone.conf
    - uses: actions/checkout@master
    - name: rclone
      uses: wei/rclone@v1
      with:
        args: --config=./rclone.conf copy ./ dropbox: -vv > ./rclone.log
    - name: delete rclone.conf
      run: |
        rm -f ./rclone.conf
